node {
 stage("Clone the project") {
    git branch: 'main', url: 'https://github.com/KamalPac/hellowebapp.git'
  }

  stage("Compilation") {
    bat "./abbrevia8/mvnw clean install -DskipTests"
  }
}